// PROYECTO TYPES
export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const GET_PROYECTOS = 'GET_PROYECTOS';
export const ADD_PROYECTO = 'ADD_PROYECTO';
export const SET_PROYECTO = 'SET_PROYECTO';
export const DELETE_PROYECTO = 'DELETE_PROYECTO';
export const ERROR_PROYECTO = 'ERROR_PROYECTO';

// TAREA TYPES
export const TAREAS_PROYECTO = 'TAREAS_PROYECTO';
export const ADD_TAREA = 'ADD_TAREA';
export const VALIDAR_FORM_TAREAS = 'VALIDAR_FORM_TAREAS';
export const DELETE_TAREA = 'DELETE_TAREA';
export const SET_TAREA = 'SET_TAREA';
export const UPDATE_TAREA = 'UPDATE_TAREA';
export const CLEAN_TAREAS = 'CLEAN_TAREAS';

// ALERTA TYPES
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

// AUTH TYPES
export const REGISTRO_OK = 'REGISTRO_OK';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const GET_USUARIO = 'GET_USUARIO';
export const LOGIN_OK = 'LOGIN_OK';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

// SPINNER TYPES
export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';

// ADMIN USERS TYPES
export const GET_USERS = 'GET_USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const SET_USER = 'SET_USER';